PORT: 8080
DB_USER: dimo
DB_PASSWORD: dimo
DB_PORT: 5432
DB_HOST: localhost
DB_NAME: trips_api
ELASTIC_HOST: localhost:9200
ELASTIC_USERNAME:
ELASTIC_PASSWORD:
ELASTIC_INDEX: devices-status-local-*
KAFKA_BROKERS: localhost:9092
TRIP_EVENT_TOPIC: topic.device.trip.event
BUNDLR_PRIVATE_KEY:
BUNDLR_NETWORK: https://devnet.bundlr.network/
BUNDLR_CURRENCY: matic
EVENTS_TOPIC: topic.event
