DB_USER: postgres
DB_PASSWORD: postgres
DB_PORT: 5433
DB_HOST: localhost
DB_NAME: pg_db
KAFKA_BROKERS: localhost:9092
JWT_KEY_SET_URL: https://auth.dev.dimo.zone/keys
DEVICES_API_GRPC_ADDR:
ELASTIC_SEARCH_ANALYTICS_HOST: localhost:9200
ELASTIC_SEARCH_ANALYTICS_USERNAME:
ELASTIC_SEARCH_ANALYTICS_PASSWORD:
ELASTIC_INDEX: devices-status-local-*
TRIP_EVENT_TOPIC: topic.device.trip.event
ETHEREUM_SIGNER_PRIVATE_KEY:
BUNDLR_NETWORK: https://devnet.bundlr.network/tx/matic
PORT: 8080
