PORT: 8080
DB_USER: dimo
DB_PASSWORD: dimo
DB_PORT: 5432
DB_HOST: localhost
DB_NAME: trips_api
ELASTIC_HOST: localhost:9200
ELASTIC_USERNAME:
ELASTIC_PASSWORD:
ELASTIC_INDEX: devices-status-local-*
KAFKA_BROKERS: localhost:9092
TRIP_EVENT_TOPIC: topic.device.trip.event
BUNDLR_PRIVATE_KEY:
BUNDLR_NETWORK: https://devnet.bundlr.network/
BUNDLR_CURRENCY: matic
EVENTS_TOPIC: topic.event
PORT: 8080
MON_PORT: 8888
DATA_FETCH_ENABLED: true
BUNDLR_ENABLED: true
WORKER_COUNT: 10
RPC_URL: "http://127.0.0.1:8545/"
CHAIN_ID: 31337
DEPLOYED_CONTRACT_PRIVATE_KEY: ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 # npx hardhat node, account 0 
DEPLOYED_CONTRACT_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
USERS_API_GRPC_ADDR: 