DB_USER: dimo
DB_PASSWORD: dimo
DB_PORT: 5432
DB_HOST: localhost
DB_NAME: trips_api
KAFKA_BROKERS: localhost:9092
JWT_KEY_SET_URL: https://auth.dev.dimo.zone/keys
DEVICES_API_GRPC_ADDR:
ELASTIC_HOST: localhost:9200
ELASTIC_USERNAME:
ELASTIC_PASSWORD:
ELASTIC_INDEX: devices-status-local-*
TRIP_EVENT_TOPIC: topic.device.trip.event
EVENT_TOPIC: topic.event
ETHEREUM_SIGNER_PRIVATE_KEY:
BUNDLR_NETWORK: https://devnet.bundlr.network/tx/matic
PORT: 8080
