apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "trips-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Release.Namespace }}/trips/db/host
      name: DB_HOST
    - key: {{ .Release.Namespace }}/trips/db/user
      name: DB_USER
    - key: {{ .Release.Namespace }}/trips/db/pass
      name: DB_PASSWORD
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/host
      name: ELASTIC_SEARCH_ANALYTICS_HOST
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/username
      name: ELASTIC_SEARCH_ANALYTICS_USERNAME
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/password
      name: ELASTIC_SEARCH_ANALYTICS_PASSWORD
