// Package docs Code generated by swaggo/swag at 2023-11-13 11:19:20.253187 -0500 EST m=+1.569225709. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/vehicle/:tokenID/trips": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists vehicle trips.",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle token id",
                        "name": "tokenID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page of trips to retrieve. Defaults to 1.",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.VehicleTripsResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api.PointTime": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                }
            }
        },
        "internal_api.VehicleTripResp": {
            "type": "object",
            "properties": {
                "end": {
                    "$ref": "#/definitions/internal_api.PointTime"
                },
                "id": {
                    "type": "string"
                },
                "start": {
                    "$ref": "#/definitions/internal_api.PointTime"
                }
            }
        },
        "internal_api.VehicleTripsResp": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                },
                "trips": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.VehicleTripResp"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "DIMO Segment API",
	Description:      "segments",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
