// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/vehicle/{tokenId}/trips": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists vehicle trips.",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle token id",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page of trips to retrieve. Defaults to 1.",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.VehicleTrips"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_DIMO-Network_trips-api_internal_api_types.Location": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "github_com_DIMO-Network_trips-api_internal_api_types.TripDetails": {
            "type": "object",
            "properties": {
                "end": {
                    "$ref": "#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.TripEnd"
                },
                "id": {
                    "type": "string",
                    "example": "2Y83IHPItgk0uHD7hybGnA776Bo"
                },
                "start": {
                    "$ref": "#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.TripStart"
                }
            }
        },
        "github_com_DIMO-Network_trips-api_internal_api_types.TripEnd": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.Location"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "github_com_DIMO-Network_trips-api_internal_api_types.TripStart": {
            "type": "object",
            "properties": {
                "estimatedLocation": {
                    "$ref": "#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.Location"
                },
                "location": {
                    "$ref": "#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.Location"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "github_com_DIMO-Network_trips-api_internal_api_types.VehicleTrips": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer",
                    "example": 1
                },
                "totalPages": {
                    "type": "integer",
                    "example": 1
                },
                "trips": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.TripDetails"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "DIMO Segment API",
	Description:      "segments",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
