basePath: /
definitions:
  internal_api.PointTime:
    properties:
      time:
        type: string
    type: object
  internal_api.VehicleTripResp:
    properties:
      end:
        $ref: '#/definitions/internal_api.PointTime'
      id:
        type: string
      start:
        $ref: '#/definitions/internal_api.PointTime'
    type: object
  internal_api.VehicleTripsResp:
    properties:
      currentPage:
        type: integer
      totalPages:
        type: integer
      trips:
        items:
          $ref: '#/definitions/internal_api.VehicleTripResp'
        type: array
    type: object
info:
  contact: {}
  description: segments
  title: DIMO Segment API
  version: "1.0"
paths:
  /vehicle/:tokenID/trips:
    get:
      description: Lists vehicle trips.
      parameters:
      - description: Vehicle token id
        in: path
        name: tokenID
        required: true
        type: integer
      - description: Page of trips to retrieve. Defaults to 1.
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_api.VehicleTripsResp'
      security:
      - BearerAuth: []
swagger: "2.0"
