basePath: /v1
definitions:
  github_com_DIMO-Network_trips-api_internal_api_types.Location:
    properties:
      latitude:
        type: number
      longitude:
        type: number
    type: object
  github_com_DIMO-Network_trips-api_internal_api_types.TripDetails:
    properties:
      droppedData:
        type: boolean
      end:
        $ref: '#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.TripEnd'
      id:
        example: 2Y83IHPItgk0uHD7hybGnA776Bo
        type: string
      start:
        $ref: '#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.TripStart'
    type: object
  github_com_DIMO-Network_trips-api_internal_api_types.TripEnd:
    properties:
      location:
        $ref: '#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.Location'
      time:
        type: string
    type: object
  github_com_DIMO-Network_trips-api_internal_api_types.TripStart:
    properties:
      estimatedLocation:
        $ref: '#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.Location'
      location:
        $ref: '#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.Location'
      time:
        type: string
    type: object
  github_com_DIMO-Network_trips-api_internal_api_types.VehicleTrips:
    properties:
      currentPage:
        example: 1
        type: integer
      totalPages:
        example: 1
        type: integer
      trips:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.TripDetails'
        type: array
    type: object
info:
  contact: {}
  description: segments
  title: DIMO Segment API
  version: "1.0"
paths:
  /vehicle/{tokenId}/trips:
    get:
      description: Lists vehicle trips.
      parameters:
      - description: Vehicle token id
        in: path
        name: tokenId
        required: true
        type: integer
      - description: Page of trips to retrieve. Defaults to 1.
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_trips-api_internal_api_types.VehicleTrips'
      security:
      - BearerAuth: []
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
