basePath: /
info:
  contact: {}
  description: segments
  title: DIMO Segment API
  version: "1.0"
paths:
  /devices/:id/segments:
    get:
      description: details for all segments associated with device
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - user-segments
swagger: "2.0"
