basePath: /
info:
  contact: {}
  description: segments
  title: DIMO Segment API
  version: "1.0"
paths:
  /vehicle/:tokenID/trips:
    get:
      description: Lists vehicle trips.
      parameters:
      - description: Vehicle token id
        in: path
        name: tokenID
        required: true
        type: integer
      - description: Page of trips to retrieve. Defaults to 1.
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
swagger: "2.0"
